# Generated by Django 4.0 on 2022-01-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
