# Generated by Django 4.0 on 2021-12-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_product_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus'),
            preserve_default=False,
        ),
    ]
