# Generated by Django 4.0 on 2021-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_id_cart_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tastingnote',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tasting_notes',
            field=models.ManyToManyField(to='products.TastingNote'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
